name: esaferide
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  google_sign_in: ^7.2.1
  flutter_facebook_auth: ^7.1.2

  # Media & files
  image_picker: ^0.8.13
  record: ^4.4.4
  path_provider: ^2.2.19
  uuid: ^3.0.7

  # Location & maps
  geolocator: ^9.0.2
  geocoding: ^2.2.2
  google_maps_flutter: ^2.18.3

  # Network & permissions
  http: ^1.6.0
  permission_handler: ^11.4.0

  # JS interop for web-specific implementations
  js: ^0.6.7
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/shuttle.png
    - assets/images/safeborder.png
    - assets/avatar_placeholder.png
    - assets/images/safelogo.png
