name: esaferide
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5

  # Media & files
  image_picker: ^1.2.1
  path_provider: ^2.0.0
  record: ^4.4.0
  uuid: ^3.0.7

  # Location & maps
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  google_maps_flutter: ^2.2.3

  # Network & permissions
  http: ^1.6.0
  permission_handler: ^11.4.0

  # Agora (ENGINE ONLY â€“ STABLE)
  agora_rtc_engine: ^6.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # MUST stay low to avoid conflicts
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/shuttle.png
    - assets/images/safeborder.png
    - assets/avatar_placeholder.png
    - assets/images/safelogo.png
